### ISSUE TITLE
I get stuck when I create WriteStream in sparkstreaming

### ISSUE THREAD

**Issue by 4d59d62a544f5477** [googleapis/java-bigquerystorage#1170]
#### Environment details
1. scala-2.12.1
2. spark-*_2.12-3.1.1
3. Windows10
4. Java-8

#### Code example

```scala
stream.foreachRDD(rdd => {
        rdd.foreachPartition(iter => {
          val client: BigQueryWriteClient = BigQueryWriteClient.create()
          val stream: WriteStream = WriteStream.newBuilder().setType(WriteStream.Type.PENDING).build()
          val table: TableName = TableName.of(projectId, datasetName, tableName)
          val createWriteStreamRequest: CreateWriteStreamRequest = CreateWriteStreamRequest.newBuilder().setParent(table.toString).setWriteStream(stream).build()
          // this line is stuck code
          val writeStream: WriteStream = client.createWriteStream(createWriteStreamRequest)
          val writer: JsonStreamWriter = JsonStreamWriter.newBuilder(writeStream.getName, writeStream.getTableSchema,client).build()
          iter.foreach(data=> {
            val jsonArray: JSONArray = new JSONArray()
            val jsonObject: JSONObject = new JSONObject()
            jsonObject.put("name", data)
            jsonArray.add(jsonObject)
            val future: ApiFuture[AppendRowsResponse] = writer.append(jsonArray)
            val response: AppendRowsResponse = future.get()
          })
          val finalizeResponse: FinalizeWriteStreamResponse = client.finalizeWriteStream(writeStream.getName)
          val commitRequest: BatchCommitWriteStreamsRequest = BatchCommitWriteStreamsRequest.newBuilder()
            .setParent(table.toString)
            .addWriteStreams(writeStream.getName)
            .build()

           val commitResponse: BatchCommitWriteStreamsResponse = client.batchCommitWriteStreams(commitRequest)
           if (!commitResponse.hasCommitTime) {
             import scala.collection.JavaConversions._
             for (err <- commitResponse.getStreamErrorsList) {
                System.out.println(err.getErrorMessage)
             }
            }
          writer.close()
          client.close()
        })
 })
```

#### Stack trace
```
I get stuck on this code 'val writeStream: WriteStream = client.createWriteStream(createWriteStreamRequest) ' all the time,
 ,either create this on the gcp-driver or gcp-executor it can't go on.but it can work on local-mode in my Windows
```

#### External references such as API reference guides
     <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>libraries-bom</artifactId>
                <version>20.7.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
     </dependencyManagement>
        <dependency>
            <groupId>org.apache.bahir</groupId>
            <artifactId>spark-streaming-pubsub_2.12</artifactId>
            <version>2.4.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigquery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-bigquerystorage</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-pubsub</artifactId>
        </dependency>
Thanks!

**Comment by stephaniewang526** [comment]
Hi, could you post this question in [this repo](https://github.com/GoogleCloudDataproc/spark-bigquery-connector) instead? They may know how to help or point you in the right direction.
