### ISSUE TITLE
Make BigQueryReadClient mockable with mockito.

### ISSUE THREAD

**Issue by ajamato** [googleapis/java-bigquerystorage#1189]
Hi, I was trying to mock our the API calls in a test in the apache beam repo. But I realized that we couldn't mock the methods on BigQueryReadClient with mockito, because they are marked final

Would it be okay if I sent a PR to remove the final qualifier?

On these methods: createReadSession
https://github.com/googleapis/java-bigquerystorage/blob/397a3db92d6220c53519cb4883bbfcd39f2a8096/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClient.java#L187

readRowsCallable()
https://github.com/googleapis/java-bigquerystorage/blob/397a3db92d6220c53519cb4883bbfcd39f2a8096/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClient.java#L287

splitReadStream()
https://github.com/googleapis/java-bigquerystorage/blob/397a3db92d6220c53519cb4883bbfcd39f2a8096/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClient.java#L315

**Comment by stephaniewang526** [comment]
We don't plan on removing the `final` keyword. Please try to use [MockBigQueryRead](https://github.com/googleapis/java-bigquerystorage/blob/397a3db92d6220c53519cb4883bbfcd39f2a8096/google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BaseBigQueryReadClientTest.java#L96).
