### ISSUE TITLE
JsonToProtoMessage.fillField can not handle null values 

### ISSUE THREAD

**Issue by kgoderis** [googleapis/java-bigquerystorage#1258]
JsonStreamWriter.append() fails when adding a JSONArray in which some fields are null because JsonToProtoMessage.fillField() does not handle null values returned by java.lang.Object val = json.get(exactJsonKeyName); (line 135). 

null values should be supported because the Schema used to create the JsonStreamWriter could contain fields with a  NULLABLE mode.

**Comment by yirutang** [comment]
For null fields, we assumed the field will simply not be there. So if a field is null, we will just ignore that field?

**Comment by kgoderis** [comment]
Yes, that is what could be done. FYI in my case the json submitted was the result of the Jackson ObjectMapper, I need to check if that one can skip null values as well. But it would be more logical for the lib to stay in line with BQ Schemas that can contain nullable fields

**Comment by yirutang** [comment]
I see. it would be an easy fix then.
