### ISSUE TITLE
BigQuery Storage v1Beta2 : PERMISSION_DENIED on TABLES_UPDATE_DATA despite having correct IAM role

### ISSUE THREAD

**Issue by kgoderis** [googleapis/java-bigquerystorage#1390]
I follow more or less the example in the official doc to tryout the v1b2 API, and I do get the above error despite having the right roles

`2021-10-28 18:05:39.424  INFO 80223 --- [        Gax-108] c.g.c.b.storage.v1beta2.StreamWriterV2   : Received done callback. Stream: projects/xxxxxxx/streams/Cic2MzhjYTEyYS0wMDAwLTJkNzYtYmQ5MC0zYzI4NmQ1MDI4ZmE6czA Final status: com.google.api.gax.rpc.PermissionDeniedException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'TABLES_UPDATE_DATA' denied on resource 'projects/xxxxxxx' (or it may not exist).`

[Obfuscated project/resource name]

Jar deployed =  google-cloud-bigquerystorage-2.0.2.jar, which is the managed version from the BOM (<artifactId>spring-cloud-gcp-starter-bigquery</artifactId>)

The code is execute with the active account here below

```
mbp:~ kgoderis$ gcloud auth list
      Credentialed Accounts
ACTIVE  ACCOUNT
*       karel.goderis@gmail.com
```

I verified access through the Policy Troubleshooter of GC Console:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/5459062/139297099-f39f7855-2d75-4eaf-9c26-ca5aef14421f.png">

and obviously, the resource does exist. Adding data via the legacy streaming API works perfectly well

What might I be missing here?

**Comment by stephaniewang526** [comment]
Were you able to initialize the client without any issue? This happens only when you're trying to stream data?

**Comment by stephaniewang526** [comment]
Hi, following up on this?

**Comment by latra** [comment]
Hi @kgoderis, here you have a [temporally fix](https://github.com/googleapis/java-bigquerystorage/blob/176dc8b1fa30cf9a9a98628bd83c9ab487ddb094/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java#L164) by adding the '"x-goog-request-params"' header

Also there is [the BEAM issue](https://issues.apache.org/jira/browse/BEAM-12344?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel) and a [PIT](https://issuetracker.google.com/207457946) case related to that
