### ISSUE TITLE
How can I use bigquery storage Read API to get the result of a query as Json Object

### ISSUE THREAD

**Issue by 1stenjoydmoment** [googleapis/java-bigquerystorage#1545]
I am trying an example from below page to read data from BQ using Storage Read API.
https://github.com/googleapis/java-bigquerystorage/blob/main/samples/snippets/src/main/java/com/example/bigquerystorage/StorageSample.java

In above Example / or with BQ Storage Read API we have only 2 formats AVRO, ARROW . May be I am overlooking something.

Is there any option available to use JSON. Ideally I want rows as JSON Object.

Can you suggest , Please ?

**Comment by stephaniewang526** [comment]
Hi, the Read API does not support returning results in JSON format. You would ned to use a converter library to convert row output from the binary format to JSON.

What is your use case?
