### ISSUE TITLE
Timestamp still not parsed correctly

### ISSUE THREAD

**Issue by dark0dave** [googleapis/java-bigquerystorage#1579]
#### Environment details

1. BigQuery storage API JSONToProtoMessage
2. OS type and version: Linux/Any
3. Java version: 11
4.  version(s): Most recent v2.11.0

#### Steps to reproduce

Create a string field in a JSONObject with schema Timestamp, value something reasonable: "2022-02-06 07:24:47.84".

Returns 1970-01-20 00:42:12.287840 UTC (In bigquery which is not correct)

1. Create a bigquery table with only one field of type TIMESTAMP and with name "d"
2. Use JsonStreamWriter with this JSON Array [{"d":"2022-02-06 07:24:47.84"}] d will be encoded into big query incorrectly.
3. Run

Linked to https://github.com/googleapis/java-bigquerystorage/issues/1515

Code:
```java
    final var tableSchema =
        TableSchema.newBuilder()
            .addFields(
                TableFieldSchema.newBuilder()
                    .setType(TIMESTAMP)
                    .setName("d")
                    .setMode(NULLABLE)
                    .build())
            .build();
```
Rest of code is identical to your sample in https://github.com/googleapis/java-bigquerystorage/blob/main/samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java except for the fact that the data is just [{"d":"2022-02-06 07:24:47.84"}]

**Comment by geirsagberg** [comment]
Can confirm. The problem seems to be in https://github.com/googleapis/java-bigquerystorage/blob/main/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java#L300 
where milliseconds is used instead of microseconds.
