### ISSUE TITLE
JsonToProtoMessage issue with TIMESTAMP fields - milliseconds vs microseconds

### ISSUE THREAD

**Issue by daniels-cysiv** [googleapis/java-bigquerystorage#1604]
#### Environment details

1. BigQuery storage API
2. OS type and version: MacOS 
3. Java version: 17
4.  version(s): 2.11.1, in gradle `implementation 'com.google.cloud:google-cloud-bigquerystorage:2.11.1'`

#### Steps to reproduce

  1. Have a table with a TIMESTAMP column
  2. Use JsonStreamWriter to set this column to a string-encoded timestamp, such as `java.sql.Timestamp.from(java.time.Instant.now()).toString()`
  3. Write data to BigQuery, commit the stream
  4. Time shows up in BigQuery as early 1970, not 2022

#### Code example

Problem is in `com.google.cloud.bigquery.storage.v1.JsonToProtoMessage` around line 307:
```
          } else if (fieldSchema.getType() == TableFieldSchema.Type.TIMESTAMP) {
            if (val instanceof String) {
              protoMsg.setField(fieldDescriptor, Timestamp.valueOf((String) val).getTime());
```
The issue is that this sets the time as milliseconds from epoch, while BigQuery expects microseconds from epoch.

There's a workaround, convert the time to micro-from-epoch in my code and set the field as a Long instead of a String, but the code in `JsonToProtoMessage` as it stands is incorrect.

**Comment by dark0dave** [comment]
Hey, this should be fixed by: https://github.com/googleapis/java-bigquerystorage/pull/1603, when 2.12.0 comes out.

**Comment by stephaniewang526** [comment]
Please upgrade the client lib version to v2.12.0 (https://github.com/googleapis/java-bigquerystorage/releases/tag/v2.12.0) which fixed this issue. Thanks!
