### ISSUE TITLE
Is the org.json:json dependency compatible?

### ISSUE THREAD

**Issue by draftcode** [googleapis/java-bigquerystorage#1724]
While using [the BQ Java client library](https://github.com/googleapis/java-bigquery), I found out org.json:json is included to the dependency. It seems it's coming from this library.

According to https://github.com/googleapis/java-bigquery/pull/1799#discussion_r793742025 from @tswast, it seems that org.json:json is not licensed under a free license. I wonder if its usage is intentional here.

**Comment by tswast** [comment]
I believe @prash-mi is working on this. Tracked in internal issue 216657461.

**Comment by prash-mi** [comment]
`org.json:json` has updated their license to `Public Domain`, closing this issue
more details @ b/216657461
