### ISSUE TITLE
Clients should be able to build DynamicMessage

### ISSUE THREAD

**Issue by dark0dave** [googleapis/java-bigquerystorage#1744]
**Is your feature request related to a problem? Please describe.**
Can be large latency in the convertJsonToProtoMessageImpl for lots of messages.

**Describe the solution you'd like**
I would like the api to accept DynamicMessages without using convertJsonToProtoMessageImpl

**Comment by yirutang** [comment]
These are public proto libs:

import com.google.protobuf.Descriptors.Descriptor;
import com.google.protobuf.Descriptors.FieldDescriptor;
import com.google.protobuf.DynamicMessage;
import com.google.protobuf.Message;

You can use them directly.

**Comment by dark0dave** [comment]
@yirutang thanks.
