### ISSUE TITLE
Handle missing/null repeated optional fields when converting Json messages to Protobuf

### ISSUE THREAD

**Issue by yenchau-google** [googleapis/java-bigquerystorage#1761]
**Problem encountered / steps to reproduce**

For repeated columns in the BigQuery TableSchema, the JsonToProtoMessage.convertJsonToProtoMessage converter [[here](https://github.com/googleapis/java-bigquerystorage/blob/095d7d59b47becf72a5e9cd3ced383fa45b04b50/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java#L110)] requires that the input Json object both contains 
- the array field, and
- it is not null.

If either of those things are not true, it fails with an error, before sending it to BigQuery

**Investigations:**

We tracked the cause of the error down to the fillRepeatedField method inside that converter, specifically [[this line](https://github.com/googleapis/java-bigquerystorage/blob/095d7d59b47becf72a5e9cd3ced383fa45b04b50/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java#L503)] which throws an error if the Json field is null or missing: jsonArray = json.getJSONArray(exactJsonKeyName);

Therefore it would be great to get this issue fixed.
Many thanks.

**Comment by Neenu1995** [comment]
Fixed.
