### ISSUE TITLE
Generated code should not be mixed with code written by people

### ISSUE THREAD

**Issue by arturowczarek** [googleapis/java-bigquerystorage#2055]
The project is partially generated by bots. They place the code into the same package where code written by people is located. This is a source of two problems:
- You are not sure which files you should modify to introduce changes. You have to read through more than it's necessary.
- The generator invoked by the bot marks the whole package (in `package-info.java`) as `@Generated`. This turns off the IntelliJ IDEA inspections. When you comment this annotation you'll see a whole host of unused fields, missing final keywords, missing parameter descriptors, etc).

**Describe the solution you'd like**
Separate generated code into dedicated package or even a separate location.

**Describe alternatives you've considered**
Commenting the `@Generated` annotation for development.

**Comment by Neenu1995** [comment]
Hi @arturowczarek,
Thanks for the suggestion. We will consider commenting `@Generated` annotation during development.
All generated files have a comment `// AUTO-GENERATED DOCUMENTATION AND CLASS.` immediately after the imports. 

Hope this helps. Feel free to reopen the issue if you have more questions or concerns.
