### ISSUE TITLE
JsonStreamWriter.Builder#setEnableConnectionPool does not obey argument passed

### ISSUE THREAD

**Issue by bastewart** [googleapis/java-bigquerystorage#2083]
#### Code example

`setEnableConnectionPool` does not obey the argument passed, instead however it is called connection pooling is enabled.

You can see this in the current master branch below (introduced - presumably by mistake! - in https://github.com/googleapis/java-bigquerystorage/pull/2048):

https://github.com/googleapis/java-bigquerystorage/blob/4fc828674fc63f398aafe822ae7d8532fb9e1a45/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java#L322-L325

Sorry, I have never contributed to this repo otherwise I'd just open a PR with a fix myself!

**Comment by Neenu1995** [comment]
Thanks for opening the issue @bastewart.
Opened [PR](https://github.com/googleapis/java-bigquerystorage/pull/2096) to fix it.

Feel free to open a PR in the future, contributors are always welcome.

**Comment by bastewart** [comment]
Thank you! 🙏

**Comment by bastewart** [comment]
Fixed in https://github.com/googleapis/java-bigquerystorage/issues/2096. Thank you!
