### ISSUE TITLE
Is it possible to write to existing stream?

### ISSUE THREAD

**Issue by snuyanzin** [googleapis/java-bigquerystorage#2198]
I started to follow example from https://cloud.google.com/bigquery/docs/write-api-streaming#exactly-once (thanks for that by the way)

which is working fine.

However in my case the app which is going to write to BQ could fail/shutdown sometimes (e.g. maintenance)
At the same time on the same doc page with example it is mentioned that
>You cannot delete a stream explicitly. Streams follow the system-defined time to live (TTL):
A committed stream has a TTL of four days if there is no traffic on the stream.
A buffered stream by default has a TTL of seven days if there is no traffic on the stream.

so if I understand correctly once app with writer is started it  creates a stream and we could name it like 
```java
final String streamName = WriteStreamName.of("[PROJECT]","[DATASET]", "[TABLE]",  "[STREAM]").toString();
WriteStream stream = WriteStream.newBuilder().setType(WriteStream.Type.COMMITTED).setName(streamName).build();
```
so far it works fine
now imagine there is some maintenance hours and the app is turned off. However as it's written committed stream has a TTL 4 days.
Am I correct that I can get this stream somehow and continue writing in it without creation a new one?

I'm asking since I tried to do it like that
```java
BigQueryWriteClient client =
              BigQueryWriteClient.create(
                      BigQueryWriteSettings.newBuilder().setCredentialsProvider(creds).build());
...
WriteStream writeStream = client.getWriteStream(GetWriteStreamRequest.newBuilder().setName(streamName).build());
if (writeStream == null) {
    stream = WriteStream.newBuilder().setType(WriteStream.Type.COMMITTED).setName(streamName).build();
}
```

however now it does not work and fails like
```
Caused by: io.grpc.StatusRuntimeException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid stream name. Entity: projects/aiven-opensource-sandbox/datasets/TestDataSet/tables/test-table/streams/_mystream
	at io.grpc.Status.asRuntimeException(Status.java:539)
	... 17 more
```

in fact have same question both for `WriteStream.Type.COMMITTED` and `WriteStream.Type.BUFFERED`

P.S. also curious if there is a way to get a list of available streams per table, currently i was not able to find any doc about it...

**Comment by GaoleMeng** [comment]
Hi Sergey,

From the log of the thrown error
```
Caused by: io.grpc.StatusRuntimeException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid stream name. Entity: projects/aiven-opensource-sandbox/datasets/TestDataSet/tables/test-table/streams/_mystream
```
It seems like you are providing a customized stream name ends with '_mystream' to the stream writer. 

That's not how exactly once stream is supposed to work. The user should create the write stream first through CreateWriteStreamRequest
I'm copying from the example link:
```
WriteStream stream = WriteStream.newBuilder().setType(WriteStream.Type.COMMITTED).build();

CreateWriteStreamRequest createWriteStreamRequest =
          CreateWriteStreamRequest.newBuilder()
              .setParent(parentTable.toString())
              .setWriteStream(stream)
              .build();
WriteStream writeStream = client.createWriteStream(createWriteStreamRequest);
```
Notice that the user does not need to explicitly provide the stream name by themselves. 

During system reboot in the situation you mentioned. It's fine for the user to just recreate a new write stream, there's currently no API to list the previously created stream on a table

**Comment by snuyanzin** [comment]
Hi @GaoleMeng 
thanks for your response

yes, I agree about exactly once, since it is committed always it is not the problem.

However the main question is about batch mentioned at (https://cloud.google.com/bigquery/docs/write-api-batch)

Sorry if I was unclear about that 

the list of steps
>1. Call CreateWriteStream to create one or more streams in pending type.
>2. For each stream, call AppendRows in a loop to write batches of records.
>3. For each stream, call FinalizeWriteStream. After you call this method, you cannot write any more rows to the stream. If you call AppendRows after calling FinalizeWriteStream, it returns a [StorageError](https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.StorageError) with StorageErrorCode.STREAM_FINALIZED in the google.rpc.Status error. For more information the google.rpc.Status error model, see [Errors](https://cloud.google.com/apis/design/errors).
>4. Call BatchCommitWriteStreams to commit the streams. After you call this method, the data becomes available for reading. If there is an error committing any of the streams, the error is returned in the stream_errors field of the [BatchCommitWriteStreamsResponse](https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#batchcommitwritestreamsresponse).

So it says that I have to call `BatchCommitWriteStreams` on streams... However it could happen that I don't have these streams after reboot. 
How i can get them to call `BatchCommitWriteStreams`?

**Comment by GaoleMeng** [comment]
Hi Sergey,

Unfortunately for PENDING mode that's the case, there's no API available to get the streams prior to the reboot.

Would COMMITTED mode be suitable for your use case: https://cloud.google.com/bigquery/docs/write-api#committed_type ?  In this mode we won't need explicit commit to be called.

**Comment by snuyanzin** [comment]
ok, I see, thanks for explanation.
I think we could live with `committed`

Just out of curiocity: are there any plans to add such feature?

**Comment by GaoleMeng** [comment]
Hi Sergey,

Currently there's no plan to adding that, as that would need non-trivial backend change to expose that. I agree this would potentially be a useful feature, but since we have COMMITTED mode so that would unblock most of the use case in our past experience.

**Comment by snuyanzin** [comment]
ok, thanks a lot for your answers
