### ISSUE TITLE
How can I increase BigQuery table download speed with the Java bigquery-storage API ?

### ISSUE THREAD

**Issue by fabiencelier** [googleapis/java-bigquerystorage#809]
I am trying to download a table of ~30GB from BigQuery to Arrow.

I am following the [documentation example](https://github.com/googleapis/java-bigquerystorage/blob/master/samples/snippets/src/main/java/com/example/bigquerystorage/StorageArrowSample.java) with the following changes:
 -  I have set the "max stream count" to 100.
 - I am reading the streams in parallel

I run this from a VM in google cloud in the same region as my big query table however my download speed seems to be limited to "only" ~250MB/s and my CPU usage is ~20%. My VM is a [e2-standard-8](https://cloud.google.com/compute/docs/machine-types#e2_standard_machine_types) (8 vCPUs, 32 GB memory) 

Neither my network bandwidth or my CPUs seems to be a limit here because I can run three times the same program in parallel and get ~700MB download speed and ~60% CPU usage. However I cannot get this speed for a single request.

How can I go faster ? Is this 250MB/s a limit by BigQuery, a limit of the API, something that I am missing ?
What maximum speed should I expect when downloading BigQuery tables with this API ?

**Comment by stephaniewang526** [comment]
@kmjung - wdyt?

**Comment by kmjung** [comment]
250 MiB/s is on the high end for the storage API at the moment. You might use profiling to verify that you're not doing anything on your end to limit client-side throughput by decoding and processing the results on the same thread that you're using to pull messages from the network, but the decoding cost of Arrow is very low, so I doubt this is the problem.

It's likely that the storage API itself is the limiting factor. In practice, even though Arrow is a columnar format and most BigQuery data is stored in columnar fashion (in [Capacitor](https://cloud.google.com/blog/products/gcp/inside-capacitor-bigquerys-next-generation-columnar-storage-format)), there's a fair amount of CPU work involved in doing the transcoding to Arrow.

As you've discovered, you can read from multiple streams in parallel to increase overall throughput. How many streams are you actually getting here?

**Comment by fabiencelier** [comment]
What is the throughput that you're getting on a single stream?

Here is the max throughput I have:
 - 1 stream: 90MiB/s
 - 2 streams: 175MiB/s
 - 3 streams: 240MiB/s
 - 4 streams or more: 250MiB/s

Even with ~40 streams I can't go beyond this limit

> It's likely that the storage API itself is the limiting factor. In practice, even though Arrow is a columnar format and most BigQuery data is stored in columnar fashion (in Capacitor), there's a fair amount of CPU work involved in doing the transcoding to Arrow.

How can I confirm that is limiting factor ?
Do I have any control on that to go faster ?

**Comment by kmjung** [comment]
@stephaniewang526 is there a way to verify that we're using separate gRPC channels for each stream here?

**Comment by stephaniewang526** [comment]
I am unaware of a way to do so.

**Comment by fabiencelier** [comment]
Why closing this issue so fast ? Isn't the max download speed of the API worth investigating a bit ?

On my side I have been playing with some settings.

I have found that I can increase the download speed if I increase the "Channel per CPU" settings:

```java
BigQueryReadSettings clientSettings =
    BigQueryReadSettings.newBuilder()
        .setTransportChannelProvider(
            InstantiatingGrpcChannelProvider.newBuilder().setChannelsPerCpu(4).build())
        .build();
BigQueryReadClient client = BigQueryReadClient.create(clientSettings)
```
I can reach ~900MB/s with this !

But I think that is poorly documented and quite hard to find :/ I was only lucky to find it by randomly trying some settings.

Would you know any other settings I can set to improve the download speed ?

**Comment by stephaniewang526** [comment]
@kmjung do you know of any other clientSettings that can improve the download speed other than `setChannelsPerCpu`?

**Comment by vam-google** [comment]
Hey @stephaniewang526! 

Unfortunately I don't remember much about it. What I still vaguely remember is below.

This is mostly for completeness, but if `InstantiatingGrpcChannelProvider.Builder.setChannelsPerCpu(multiplier)` is used, please keep in mind that there are two other methods in the same class which do exactly the same thing but have different semantics: `setChannelsPerCpu(multiplier, maxChannels)` and  `setPoolSize(poolSize)`.

`setChannelsPerCpu(multiplier)` calls `setChannelsPerCpu(multiplier, maxChannels)` which calls `setPoolSize(poolSize)`. So all three methods are related and are just 3 different ways to set the same value (`poolSize`), with `setPoolSize(poolSize)` being the most direct one. At the same time `setChannelsPerCpu(multiplier)` imposes an implicit maximum size of the pool as `100`, and `setPoolSize(poolSize)` as `1000` (i.e. the maximum channel pool size you can theoretically get with any GAPIC library is 1000). 

I.e. on monster machines (like 32+ cores), `setChannelsPerCpu(4)`, will lead to `32*4 = 128`, but that is bigger than `100` so the pool size will be set to `100`. To overcome that you can set `setPoolSize(128)` instead. `setPoolSize(1000)` and bigger will start throwing an exception.

You can also try playing with the Thread Pool Executor pool size, which determines maximum number of threads the client will be able to use for everything it does (and it is connected to the channels config as well). Basically look into `BigQueryReadSettings.newBuilder().setExecutorProvider()` direction. By default all of the clients are configured with the thread pool size being equal to the number of cores on the machine it runs, but not less than 4 threads. You can experiment with that value.

The configs above are not gRCP-specific, strictly speaking. They are GAPIC-specific (the generated client, which wraps gRPC). gRPC also has some very low level configs, but if used via GAPIC they are not supposed to be touched directly (and either way I don't know/remember much about them). 

I hope that helps.

**Comment by stephaniewang526** [comment]
Closing this ticket. We can reopen if more questions come up.

**Comment by fabiencelier** [comment]
Thank you for the detailed answer about these settings !

In the end we managed to reach 1.5GB/s on a 16CPU machine, which is very good :)
