### ISSUE TITLE
[bigquerystorage, Java] Reconnect on "EOS on DATA frame" Internal Server Errors

### ISSUE THREAD

**Issue by stephaniewang526** [googleapis/java-bigquerystorage#86]
original ticket: b/146489609

#### copy from bug
The Java client needs to reconnect to the BigQuery Storage stream when an "EOS on DATA frame" error occurs.

See: https://groups.google.com/a/google.com/d/topic/cloud-dpes-bigquery/dzvlD5O00a0/discussion for discussion.

Implementation in Python: https://github.com/googleapis/google-cloud-python/pull/9994

**Comment by stephaniewang526** [comment]
Looks like Java's implementation was implemented already: https://github.com/googleapis/java-bigquerystorage/blob/master/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ReadRowsResumptionStrategy.java

**Comment by pakio** [comment]
we run into the same problem. do you have any plan for fixing this?

**Comment by stephaniewang526** [comment]
We're working on #263 which should fix this.
